apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-pdb
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- if .Values.migration.existingSelectors.enabled }}
        {{- toYaml .Values.migration.existingSelectors.selectors | nindent 6 }}
      {{- else }}
        {{ include "aspnetcore.selectorLabels" . | nindent 6 }}
      {{- end }}
