apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-pdb
spec:
  minAvailable: {{ .Values.PodDisruptionBudget.MinAvailable }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
