{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aspnetcore.serviceAccountName" . }}
  labels:
    {{- include "aspnetcore.standardLabels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.azureWorkloadIdentity.enabled }}
    # https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview#pod-labels
    azure.workload.identity/use: "true"
    {{- end }}
  annotations:
    {{- if .Values.azureWorkloadIdentity.enabled }}
    {{- if .Values.azureWorkloadIdentity.clientId }}
    # https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview#service-account-annotations
    azure.workload.identity/client-id: {{ .Values.azureWorkloadIdentity.clientId | quote }}
    {{- end }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
