name: Deploy pages

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["Release charts"]
    types: [completed]
  push:
    branches: [main]
    paths: ["pages/**/*"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Setup Pages
        uses: actions/configure-pages@7110e9e03ffb4a421945e5d0607007b8e9f1f52b # v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@253fd476ed429e83b7aae64a92a75b4ceb1a17cf # v1
        with:
          path: "./pages/"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@e690f03220f8a0e2d4da521d8b3a50e0b52650e0 # v1
