name: Semgrep scan

on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}
  schedule:
    - cron: "32 7 * * 6"

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep@sha256:e0db2a8ba9eb59492c72008ef36bcdcc66ca04c783fabe6f10ad379f724cf9fb

    steps:
      - name: Checkout all commits and tags
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        if: ${{ github.event_name == 'pull_request' }}
        with:
          fetch-depth: 0

      - name: Checkout single commit
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        if: ${{ github.event_name != 'pull_request' }}

      - name: Pull request scan
        if: ${{ github.event_name == 'pull_request' }}
        run: semgrep scan --config=auto --verbose --time --error --baseline-commit ${{ github.event.pull_request.base.sha }}

      - name: Full scan
        if: ${{ github.event_name != 'pull_request' }}
        run: semgrep scan --config=auto --verbose --time --sarif --output report.sarif

      - name: Save report as pipeline artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: report.sarif
          path: report.sarif

      - name: Publish code scanning alerts
        if: ${{ github.event_name != 'pull_request' }}
        uses: github/codeql-action/upload-sarif@32dc499307d133bb5085bae78498c0ac2cf762d5 # v2
        with:
          sarif_file: report.sarif
          category: semgrep
