name: Semgrep scan

on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}
  schedule:
    - cron: "32 7 * * 6"

jobs:
  semgrep:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    container:
      image: returntocorp/semgrep@sha256:ff93a38e78dbaa03c97c48f95bcf2ab4512256eb336fc3e8c92c8d002bbfc059

    steps:
      - name: Checkout all commits and tags
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        if: ${{ github.event_name == 'pull_request' }}
        with:
          fetch-depth: 0

      - name: Checkout single commit
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        if: ${{ github.event_name != 'pull_request' }}

      - name: Pull request scan
        if: ${{ github.event_name == 'pull_request' }}
        run: semgrep scan --config=auto --verbose --time --error --baseline-commit ${{ github.event.pull_request.base.sha }}

      - name: Full scan
        if: ${{ github.event_name != 'pull_request' }}
        run: semgrep scan --config=auto --verbose --time --sarif --output report.sarif

      - name: Save report as pipeline artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: report.sarif
          path: report.sarif

      - name: Publish code scanning alerts
        if: ${{ github.event_name != 'pull_request' }}
        uses: github/codeql-action/upload-sarif@74483a38d39275f33fcff5f35b679b5ca4a26a99 # v2
        with:
          sarif_file: report.sarif
          category: semgrep
