name: Semgrep scan

on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}
  schedule:
    - cron: "32 7 * * 6"

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep@sha256:0c68b1e21a24ef4ad14927a64e5b0196be7b9cda65c422f15951a9f8f842726e

    steps:
      - name: Checkout all commits and tags
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        if: ${{ github.event_name == 'pull_request' }}
        with:
          fetch-depth: 0

      - name: Checkout single commit
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        if: ${{ github.event_name != 'pull_request' }}

      - name: Pull request scan
        if: ${{ github.event_name == 'pull_request' }}
        run: semgrep scan --config=auto --verbose --time --error --baseline-commit ${{ github.event.pull_request.base.sha }}

      - name: Full scan
        if: ${{ github.event_name != 'pull_request' }}
        run: semgrep scan --config=auto --verbose --time --sarif --output report.sarif

      - name: Save report as pipeline artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: report.sarif
          path: report.sarif

      - name: Publish code scanning alerts
        if: ${{ github.event_name != 'pull_request' }}
        uses: github/codeql-action/upload-sarif@83f0fe6c4988d98a455712a27f0255212bba9bd4 # v2
        with:
          sarif_file: report.sarif
          category: semgrep
