name: Semgrep scan

on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}
  schedule:
    - cron: "32 7 * * 6"

jobs:
  semgrep:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    container:
      image: returntocorp/semgrep@sha256:fa8fe75399d1413ee1e2b1591d5cae02c9ccd69a39c58fa9d05f7df0fc999017

    steps:
      - name: Checkout all commits and tags
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          fetch-depth: 0

      - name: Checkout single commit
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        if: ${{ github.event_name != 'pull_request' }}

      - name: Pull request scan
        if: ${{ github.event_name == 'pull_request' }}
        run: semgrep scan --config=auto --verbose --time --error --baseline-commit ${{ github.event.pull_request.base.sha }}

      - name: Full scan
        if: ${{ github.event_name != 'pull_request' }}
        run: semgrep scan --config=auto --verbose --time --sarif --output report.sarif

      - name: Save report as pipeline artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: report.sarif
          path: report.sarif

      - name: Publish code scanning alerts
        if: ${{ github.event_name != 'pull_request' }}
        uses: github/codeql-action/upload-sarif@8b7fcbfac2aae0e6c24d9f9ebd5830b1290b18e4 # v2
        with:
          sarif_file: report.sarif
          category: semgrep
